env = DefaultEnvironment()
src = [
    'fnn_common.f90', 
    'fnn_activation_linear.f90', 
    'fnn_activation_nonlinear.f90', 
    'fnn_activation_tanh.f90', 
    'fnn_layer.f90', 
    'fnn_layer_dense.f90',
    'fnn_layer_normalisation.f90',
    'fnn_network_sequential.f90',
]

env.Program('test_3.x', ['test_3.f90']+src)
env.Program('test_4.x', ['test_4.f90']+src)
env.Program('test_5.x', ['test_5.f90']+src)
env.Program('test_6.x', ['test_6.f90']+src)
env.Program('test_7.x', ['test_7.f90']+src)

